name: ðŸš€ Deploy Laravel to cPanel via FTP

on:
  push:
    branches:
      - main # Ganti jika branch deploy kamu berbeda

jobs:
  deploy:
    name: Upload Files via FTP
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¦ Checkout Repo
        uses: actions/checkout@v3

      - name: ðŸ§° Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: ðŸ›  Install Dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          npm ci --legacy-peer-deps
          npm run build

      - name: ðŸš€ Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 145.79.14.32
          username: u248076115.mbahban
          password: PenakNgene123!
          server-dir: /
          local-dir: ./
          exclude: |
            **/.git*
            **/.github*
            node_modules/**
            vendor/**
            tests/**
            .env
            .env.*
            storage/debugbar
            storage/logs
            storage/framework/cache
